/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package theoriegraphes;

import javafx.*;
import javafx.embed.swing.JFXPanel;
import javafx.scene.Scene;
import javafx.scene.layout.VBox;
import javafx.scene.web.WebView;
import algos.BFS;
import algos.BellmanFord;
import algos.DFS;
import algos.Dijikstra;
import algos.FordFolkersonResiduelle;
import algos.FordForlkersonMarquage;
import algos.Kruscal;
import algos.Prim;
import algos.Wireshall;
import algos.WelchPowell;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfDocument;
import com.itextpdf.text.pdf.PdfWriter;
import com.sun.javafx.application.PlatformImpl;
import com.sun.media.jfxmediaimpl.platform.Platform;

import java.awt.AWTException;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JColorChooser;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;
import metier.Arret;
import metier.Configuration;
import metier.Sommet;

/**
 *
 * @author abdel
 */
public class MainFrame extends javax.swing.JFrame {
    private static MainFrame instance;
    public static MainFrame getInstance(){
        if(instance==null){
            instance = new MainFrame();
        }
        return instance;
    }
    
    private MainFrame() {
        initComponents();
    }
    
    public void setCentrePanel(JPanel p){
        jScrollPane2.setViewportView(p);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        btn_bfs = new javax.swing.JButton();
        btn_dfs = new javax.swing.JButton();
        btn_matrice = new javax.swing.JButton();
        btn_prim = new javax.swing.JButton();
        btn_kruskal = new javax.swing.JButton();
        btn_restore = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btn_wireshall = new javax.swing.JButton();
        btn_dijikstra = new javax.swing.JButton();
        btn_billmanford = new javax.swing.JButton();
        btn_fordfolkerson1 = new javax.swing.JButton();
        btn_fordfolkerson2 = new javax.swing.JButton();
        btn_WelchPowell = new javax.swing.JButton();
        btn_enregistrer = new javax.swing.JButton();
        
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jLabel8 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        menuInitial1 = new theoriegraphes.MenuInitial();
        jSplitPane3 = new javax.swing.JSplitPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        console = new javax.swing.JTextArea();
        btn_exporter_pdf = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_mode_emploi = new javax.swing.JButton();
        label_v = new javax.swing.JLabel();
        label_e = new javax.swing.JLabel();
        label_d = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setResizeWeight(1.0);

        btn_bfs.setText("BFS");
        btn_bfs.setEnabled(false);
        btn_bfs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bfsActionPerformed(evt);
            }
        });

        btn_dfs.setText("DFS");
        btn_dfs.setEnabled(false);
        btn_dfs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dfsActionPerformed(evt);
            }
        });

        btn_matrice.setText("Matrice d'Adjacence");
        btn_matrice.setEnabled(false);
        btn_matrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_matriceActionPerformed(evt);
            }
        });

        btn_prim.setText("Prim");
        btn_prim.setEnabled(false);
        btn_prim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_primActionPerformed(evt);
            }
        });

        btn_kruskal.setText("Kruskal");
        btn_kruskal.setEnabled(false);
        btn_kruskal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kruskalActionPerformed(evt);
            }
        });

        btn_restore.setText("Restaurer");
        btn_restore.setEnabled(false);
        btn_restore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_restoreActionPerformed(evt);
            }
        });

        jButton7.setText("arretes");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel4.setBackground(Color.RED);
        jLabel4.setOpaque(true);

        jLabel5.setBackground(Color.green);
        jLabel5.setOpaque(true);

        jButton8.setText("sommets");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("label");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel6.setBackground(Color.black);
        jLabel6.setOpaque(true);

        btn_wireshall.setText("Wareshall");
        btn_wireshall.setEnabled(false);
        btn_wireshall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_wireshallActionPerformed(evt);
            }
        });

        btn_dijikstra.setText("Dijekstra");
        btn_dijikstra.setEnabled(false);
        btn_dijikstra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dijikstraActionPerformed(evt);
            }
        });

        btn_billmanford.setText("Billman Ford");
        btn_billmanford.setEnabled(false);
        btn_billmanford.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_billmanfordActionPerformed(evt);
            }
        });

        btn_fordfolkerson1.setText("Ford Fullkirson (marquage)");
        btn_fordfolkerson1.setEnabled(false);
        btn_fordfolkerson1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fordfolkerson1ActionPerformed(evt);
            }
        });

        btn_fordfolkerson2.setText("Ford Fullkirson (residuel)");
        btn_fordfolkerson2.setEnabled(false);
        btn_fordfolkerson2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fordfolkerson2ActionPerformed(evt);
            }
        });
        
        btn_WelchPowell.setText("WelchPowell (Coloriage)");
        btn_WelchPowell.setEnabled(false);
        btn_WelchPowell.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_WelchPowellActionPerformed(evt);
            }
        });

        btn_enregistrer.setText("Enregistrer");
        btn_enregistrer.setEnabled(false);
        btn_enregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enregistrerActionPerformed(evt);
            }
        });

        jButton2.setText("BFS/DFS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setBackground(Color.blue);
        jLabel7.setOpaque(true);

        jSlider1.setMaximum(5000);
        jSlider1.setValue(1000);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });

        jLabel8.setText("Temps d'annimation:");

        jButton4.setText("Recommencer");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_bfs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_dfs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_matrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_prim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_kruskal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(btn_wireshall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_dijikstra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_billmanford, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_fordfolkerson1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_fordfolkerson2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_WelchPowell, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_restore, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_enregistrer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel4, jLabel5, jLabel6, jLabel7});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton2, jButton7, jButton8});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_matrice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_restore)
                    .addComponent(btn_enregistrer))
                .addGap(18, 18, 18)
                .addComponent(btn_bfs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_dfs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_prim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_kruskal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_wireshall)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_dijikstra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_billmanford)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_fordfolkerson1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_fordfolkerson2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_WelchPowell)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton9)
                        .addComponent(jLabel6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jButton7)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton7, jLabel4, jLabel5, jLabel6, jLabel7});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_enregistrer, btn_restore});

        jSplitPane2.setLeftComponent(jPanel1);

        jScrollPane2.setViewportView(menuInitial1);

        jSplitPane2.setRightComponent(jScrollPane2);

        jSplitPane1.setLeftComponent(jSplitPane2);

        jSplitPane3.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane3.setResizeWeight(1.0);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Trace"));

        console.setEditable(false);
        console.setColumns(20);
        console.setRows(5);
        jScrollPane1.setViewportView(console);

        btn_exporter_pdf.setText("Exporter PDF");
        btn_exporter_pdf.setEnabled(false);
        btn_exporter_pdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exporter_pdfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btn_exporter_pdf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_exporter_pdf)
                .addContainerGap())
        );

        jSplitPane3.setRightComponent(jPanel5);

        jLabel1.setText("Nombre de sommets (|V|):");

        jLabel2.setText("Nombre d'arrets(|E|):");

        jLabel3.setText("Densite (d):");

        btn_mode_emploi.setText("Guide d'utilisation");
        btn_mode_emploi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mode_emploiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_mode_emploi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(label_v, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(label_d, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(label_e, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_mode_emploi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(label_v))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(label_e))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(label_d))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, label_v});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel3, label_d});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel2, label_e});

        jScrollPane3.setViewportView(jPanel2);

        jSplitPane3.setLeftComponent(jScrollPane3);

        jSplitPane1.setRightComponent(jSplitPane3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1228, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_matriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_matriceActionPerformed
        new MatriceAdj(this, Canvas.getInstance().getGraphe().matriceAdj(), Canvas.getInstance().getGraphe().getSommets()).setVisible(true);
//        for(int i=0;i<Canvas.getInstance().getGraphe().matriceAdj().length;i++){
//            for(int j=0;j<Canvas.getInstance().getGraphe().matriceAdj()[i].length;j++){
//                System.out.print(Canvas.getInstance().getGraphe().matriceAdj()[i][j]+" ");
//            }
//            System.out.println("");
//        }
    }//GEN-LAST:event_btn_matriceActionPerformed

    private void btn_bfsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bfsActionPerformed
        if(Canvas.getInstance().getSelectionne()!=null){
            new Thread(new BFS(Canvas.getInstance().getGraphe(), Canvas.getInstance().getSelectionne())).start();
        }else{
            
        }
        
    }//GEN-LAST:event_btn_bfsActionPerformed
    
    private void btn_WelchPowellActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_btn_bfsActionPerformed
            new Thread(new WelchPowell(Canvas.getInstance().getGraphe())).start();
        
        
    }//GEN-LAST:event_btn_bfsActionPerformed

    
    private void btn_dfsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dfsActionPerformed
        if(Canvas.getInstance().getSelectionne()!=null){
            new Thread(new DFS(Canvas.getInstance().getGraphe(), Canvas.getInstance().getSelectionne())).start();
        }else{
            
        }
    }//GEN-LAST:event_btn_dfsActionPerformed

    private void btn_primActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_primActionPerformed
        new Thread(new Prim(Canvas.getInstance().getGraphe())).start();
    }//GEN-LAST:event_btn_primActionPerformed

    private void btn_kruskalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kruskalActionPerformed
        new Thread(new Kruscal(Canvas.getInstance().getGraphe())).start();
    }//GEN-LAST:event_btn_kruskalActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        JColorChooser jcc = new JColorChooser(Configuration.coleur_arret);
        JColorChooser.createDialog(MainFrame.getInstance(), "choisir une coleur", true, jcc, null, null).setVisible(true);
        Configuration.coleur_arret = jcc.getColor();
        jLabel4.setBackground(jcc.getColor());
        if(Canvas.getInstance()!=null)Canvas.getInstance().getGraphe().repaint();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        JColorChooser jcc = new JColorChooser(Configuration.coleur_sommet);
        JColorChooser.createDialog(MainFrame.getInstance(), "choisir une coleur", true, jcc, null, null).setVisible(true);
        Configuration.coleur_sommet = jcc.getColor();
        jLabel5.setBackground(jcc.getColor());
        if(Canvas.getInstance()!=null)Canvas.getInstance().getGraphe().repaint();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        JColorChooser jcc = new JColorChooser(Configuration.coleur_label);
        JColorChooser.createDialog(MainFrame.getInstance(), "choisir une coleur", true, jcc, null, null).setVisible(true);
        Configuration.coleur_label = jcc.getColor();
        jLabel6.setBackground(jcc.getColor());
        if(Canvas.getInstance()!=null)Canvas.getInstance().getGraphe().repaint();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void btn_wireshallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_wireshallActionPerformed
        new Thread(new Wireshall(Canvas.getInstance().getGraphe())).start();
    }//GEN-LAST:event_btn_wireshallActionPerformed

    private void btn_restoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_restoreActionPerformed
          Configuration.restore();
    }//GEN-LAST:event_btn_restoreActionPerformed

    private void btn_dijikstraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dijikstraActionPerformed
        if(Canvas.getInstance().getSelectionne()!=null){
            new Thread(new Dijikstra(Canvas.getInstance().getGraphe(), Canvas.getInstance().getSelectionne())).start();
        }else{
            
        }
    }//GEN-LAST:event_btn_dijikstraActionPerformed

    private void btn_exporter_pdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exporter_pdfActionPerformed
        JFileChooser file_chooser = new JFileChooser();
        file_chooser.setFileFilter(new FileNameExtensionFilter("Fichiers pdf", new String[]{"pdf","PDF"}));
        String chemin=null;
        
        if(file_chooser.showDialog(MainFrame.instance, "Exporter vers")==0) {
	        if(file_chooser.getSelectedFile().exists()) {       	
	        	if(JOptionPane.showConfirmDialog(MainFrame.instance, "Voulez vous vraiments ecraser lecontenu du fichier!!", "Fichier deja Exist!!!", JOptionPane.WARNING_MESSAGE )!=0)return;
	        	chemin = file_chooser.getSelectedFile().getAbsolutePath();
	        }
	        if(chemin==null)chemin = file_chooser.getSelectedFile().getAbsolutePath()+".pdf";
            try {
                FileOutputStream fos = new FileOutputStream(new File(chemin));
                Document document = new Document();
                PdfWriter.getInstance(document, fos);
                document.open();
                document.add(new Paragraph("Rapport d'application d'algorithme: "+Configuration.current_algo.getNom()));
                File fichier_tmp = File.createTempFile("tmp", ".png");
                BufferedImage bf=Configuration.images.get(0);
                ImageIO.write(bf, "png", fichier_tmp);
                document.add(new Paragraph("Graphe initial: "));
                document.add(Image.getInstance(fichier_tmp.toURI().toURL()));
                document.add(new Paragraph("Trace: "));
                document.add(new Paragraph(Configuration.current_algo.getTrace().toString()));
                document.add(new Paragraph("Trace - image pour chaque etape: "));
                for(int i=1;i<Configuration.images.size();i++){
                    ImageIO.write(Configuration.images.get(i), "png", fichier_tmp);
                    document.add(Image.getInstance(fichier_tmp.toURI().toURL()));
                }
                document.close();
            } catch (DocumentException | FileNotFoundException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
              
                
        }
        
    }//GEN-LAST:event_btn_exporter_pdfActionPerformed

    private void btn_mode_emploiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mode_emploiActionPerformed
        if (Desktop.isDesktopSupported())
        {
            try
            {
            	PlatformImpl.startup(
            			()->{
            				JFrame web = new JFrame("Guide d'utilisation");

            		        WebView webView = new WebView();

            		        URL url = this.getClass().getResource("/UserGuide/Guide.html");
            		        webView.getEngine().load(url.toString());

            		        VBox vBox = new VBox(webView);
            		        Scene scene = new Scene(vBox, 960, 600);

            		        JFXPanel pan = new JFXPanel();
            		        pan.setScene(scene);
            		        
            		        web.add(pan);
            		        web.setVisible(true);
            		        web.pack();
            			}
            			);          
            } catch (Exception ex)
            {
                System.out.println(ex);
            }
        }
    }//GEN-LAST:event_btn_mode_emploiActionPerformed

    private void btn_enregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enregistrerActionPerformed
        Configuration.backup();
    }//GEN-LAST:event_btn_enregistrerActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JColorChooser jcc = new JColorChooser(Configuration.coleur_label);
        JColorChooser.createDialog(MainFrame.getInstance(), "choisir une coleur", true, jcc, null, null).setVisible(true);
        Configuration.coleur_parcour = jcc.getColor();
        jLabel7.setBackground(jcc.getColor());
        if(Canvas.getInstance()!=null)Canvas.getInstance().getGraphe().repaint();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        Configuration.sleep_time = jSlider1.getValue();
    }//GEN-LAST:event_jSlider1StateChanged

    private void btn_billmanfordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_billmanfordActionPerformed
        if(Canvas.getInstance().getSelectionne()!=null){
            new Thread(new BellmanFord(Canvas.getInstance().getGraphe(), Canvas.getInstance().getSelectionne())).start();
        }else{
            
        }
    }//GEN-LAST:event_btn_billmanfordActionPerformed

    private void btn_fordfolkerson2ActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_btn_fordfolkerson2ActionPerformed
        new Thread(new FordFolkersonResiduelle(Canvas.getInstance().getGraphe(), Canvas.getInstance().getGraphe().getS(),Canvas.getInstance().getGraphe().getP())).start();
    }//GEN-LAST:event_btn_fordfolkerson2ActionPerformed

    private void btn_fordfolkerson1ActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_btn_fordfolkerson1ActionPerformed
    	new Thread(new FordForlkersonMarquage(Canvas.getInstance().getGraphe(), Canvas.getInstance().getGraphe().getS(),Canvas.getInstance().getGraphe().getP())).start();
    }//GEN-LAST:event_btn_fordfolkerson1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Canvas.instance = null;
        MainFrame.getInstance().setCentrePanel(new MenuInitial());
        
        Configuration.checkAlgos();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainFrame.getInstance().setCentrePanel(new MenuInitial());
                MainFrame.getInstance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btn_bfs;
    public static javax.swing.JButton btn_billmanford;
    public static javax.swing.JButton btn_dfs;
    public static javax.swing.JButton btn_dijikstra;
    public static javax.swing.JButton btn_enregistrer;
    public static javax.swing.JButton btn_exporter_pdf;
    public static javax.swing.JButton btn_fordfolkerson1;
    public static javax.swing.JButton btn_fordfolkerson2;
    public static javax.swing.JButton btn_kruskal;
    public static javax.swing.JButton btn_matrice;
    public static javax.swing.JButton btn_WelchPowell;
    private javax.swing.JButton btn_mode_emploi;
    public static javax.swing.JButton btn_prim;
    public static javax.swing.JButton btn_restore;
    public static javax.swing.JButton btn_wireshall;
    public static javax.swing.JTextArea console;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JSplitPane jSplitPane3;
    public static javax.swing.JLabel label_d;
    public static javax.swing.JLabel label_e;
    public static javax.swing.JLabel label_v;
    private theoriegraphes.MenuInitial menuInitial1;
    // End of variables declaration//GEN-END:variables
}
